ci(checks): commitlint precommit and ci, just commands runner (#40)
* test(checks): test

* test(checks): test

* test(checks): test

* ci(checks): commit msg hook and commitlint ci wf

Signed-off-by: Saucisse à roulettes <gaelmonach123@live.fr>

* ci(checks): commitlint push trigger

Signed-off-by: Saucisse à roulettes <gaelmonach123@live.fr>

* ci(checks): replace pull-request trigger by push trigger

Signed-off-by: Saucisse à roulettes <gaelmonach123@live.fr>

* docs(just): new just command runner documentation

update README.md and install.md

Signed-off-by: Saucisse à roulettes <gaelmonach123@live.fr>

---------

Signed-off-by: Saucisse à roulettes <gaelmonach123@live.fr>

diff --git a/hooks/commit-msg b/hooks/commit-msg
--- a/hooks/commit-msg
+++ b/hooks/commit-msg
@@ -18,3 +18,40 @@
 #  * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 #  */
 #
+
+message=$(cat .git/COMMIT_EDITMSG | commitlint)
+exit_code=$?
+
+if [[ $exit_code -ne 0 ]]; then
+    echo $message
+    exit 1
+fi
+
+# Function to run a command and check its exit code
+run_command() {
+    local message
+    local exit_code
+    message=$(poetry run $1 2>&1)
+    exit_code=$?
+
+    # Check if the command failed
+    if [[ $exit_code -ne 0 ]]; then
+        echo "Pre-commit hooks failed. Aborting commit. Details: $message"
+        exit 1
+    fi
+}
+
+# Run Black silently
+echo "Running Black..."
+run_command "black --check ."
+
+# Run Mypy silently
+echo "Running Mypy..."
+run_command "mypy ."
+
+# Run Pytest silently
+echo "Running Pytest..."
+run_command "pytest"
+
+echo "All pre-commit hooks passed."
+exit 0
